/** @format */
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopBar from "../components/layout/Topbar";
import { Toaster } from "react-hot-toast";
import { ClerkProvider } from "@clerk/nextjs";
import Footer from "@/components/layout/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 
  return (
   
    <html lang='en'>
      <body
     className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
           <ClerkProvider  
           signInUrl="/sign-in"
           signUpUrl="/sign-up"
           afterSignOutUrl="/" >

           <Toaster position="top-center" /> 
           <TopBar/>
          {children}
           <Footer/>
           
          </ClerkProvider>
      </body>
    </html>
    
  );
}
